### ISSUE TITLE
Container init fails 

### ISSUE THREAD

**Issue by jleaders** [libresh/compose-nextcloud#12]
First time using docker-compose, so I may be doing it wrong. I keep getting this cryptic error.

```
sudo docker-compose up
nextcloud_db_1 is up-to-date
nextcloud_app_1 is up-to-date
nextcloud_cron_1 is up-to-date
Starting nextcloud_web_1

ERROR: for web  Cannot start service web: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/home/jonny/Projects/owncloud/nextcloud/nginx.conf\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/052e14aea7ef617c5f13c124ed8b8abd0580c2379562d5425b522b42762f47e2\\\" at \\\"/var/lib/docker/aufs/mnt/052e14aea7ef617c5f13c124ed8b8abd0580c2379562d5425b522b42762f47e2/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

**Comment by jodumont** [comment]
When this kind of error arrive to me
it's often a typo error into my docker-compose.yml
such missing a indentation or ./ at the definition of my volume

In your case I'll give a look for nginx.conf
did you clone the repository ?
because nginx.conf refer to this [file](https://github.com/indiehosters/nextcloud/blob/master/nginx.conf)

also look if nginx.conf is not a directory instead of a file
it's happen sometimes !!

**Comment by pierreozoux** [comment]
Closing as old, and we migrate to another repo https://lab.libreho.st/libre.sh/compose/nextcloud

Feel free to reopen there.
